_target_: transformers.TrainingArguments
bf16: ${bf16}
max_grad_norm: ${max_grad_norm}
per_device_train_batch_size: ${per_device_train_batch_size}
per_device_eval_batch_size: ${per_device_eval_batch_size}
gradient_accumulation_steps: ${gradient_accumulation_steps}
tpu_num_cores: ${tpu_num_cores}
evaluation_strategy: ${evaluation_strategy}
num_train_epochs: ${num_train_epochs}
output_dir: ${output_dir}
save_strategy: ${save_strategy}
save_steps: ${save_steps}
save_total_limit: ${save_total_limit}
logging_strategy: ${logging_strategy}
logging_steps: ${logging_steps}
logging_dir: ${logging_dir}
report_to: ${report_to}
push_to_hub: ${push_to_hub}