_target_: src.datasets.causallm_dataset.StructuralDataset
data_path: ${data_dir}
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
instruction_column_name: ${instruction_column_name}
data_column_name: ${data_column_name}
target_column_name: ${target_column_name}
max_length: ${max_length}
model_path: ${model_path}
padding_side: ${padding_side}